version: '2.4'
services:
  dg-postgres:
    container_name: dg.postgres
    image: postgres:14-alpine
    command: ["postgres"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=diagraph
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - dg-network

  dg-redis:
    container_name: dg.redis
    image: redis:7.0.0-alpine
    command: ["redis-server"]
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - dg-network

  dg-mailhog:
    container_name: dg.mailhog
    image: mailhog/mailhog
    command: ["mailhog"]
    ports:
      - "1025:1025"
      - "8025:8025"
    expose:
      - "1025"
    networks:
      - dg-network

networks:
  dg-network:
    name: dg-network
