FROM mcr.microsoft.com/dotnet/sdk:6.0

ENV DOTNET_USE_POLLING_FILE_WATCHER="1"
ENV DOTNET_WATCH_RESTART_ON_RUDE_EDIT="1"
ENV ASPNETCORE_ENVIRONMENT="Docker"
ENV ASPNETCORE_HTTPS_PORT="7053"
ENV ASPNETCORE_URLS="https://*:7053"

RUN dotnet dev-certs https --clean && \
dotnet dev-certs https && \
dotnet dev-certs https --trust
ENTRYPOINT ["dotnet", "watch", "run", "--project", "/app/Diagraph.Api"]

